ZIVA_ANIMATION = "__ziva_animation"
ZIVA_ANIMATION_START = "__ziva_animation_start"
ZIVA_ANIMATION_END = "__ziva_animation_end"
ZIVA_ANIMATION_TRANSITION = "__ziva_animation_transition"
ZIVA_ANIMATION_CONTAINER = "__ziva_animation_container"
ZIVA_ANIMATION_MOVER = "__ziva_animation_mover"
ZIVA_SOLVER_PARENT = "__ziva_solver_parent"